In [1]:
# Dependencies and Setup
import pandas as pd
from pathlib import Path

In [2]:

# File to Load
vaccinations_data_to_load = Path("../Resources/vaccinations.csv")


# Read data set
vaccinations_data = pd.read_csv(vaccinations_data_to_load)

vaccinations_data.head()

,date,location_key,new_persons_vaccinated,cumulative_persons_vaccinated,new_persons_fully_vaccinated,cumulative_persons_fully_vaccinated,new_vaccine_doses_administered,cumulative_vaccine_doses_administered,new_persons_vaccinated_pfizer,cumulative_persons_vaccinated_pfizer,...,new_persons_fully_vaccinated_janssen,cumulative_persons_fully_vaccinated_janssen,new_vaccine_doses_administered_janssen,cumulative_vaccine_doses_administered_janssen,new_persons_vaccinated_sinovac,total_persons_vaccinated_sinovac,new_persons_fully_vaccinated_sinovac,total_persons_fully_vaccinated_sinovac,new_vaccine_doses_administered_sinovac,total_vaccine_doses_administered_sinovac
0,2021-01-25,AD,NaN,576.0,NaN,NaN,NaN,576.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2021-02-01,AD,460.0,1036.0,NaN,NaN,460.0,1036.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2021-02-10,AD,255.0,1291.0,NaN,NaN,255.0,1291.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2021-02-12,AD,331.0,1622.0,NaN,NaN,331.0,1622.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2021-02-19,AD,519.0,2141.0,NaN,NaN,519.0,2141.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
# Clean up data set 

cleaned_vaccinations_data = vaccinations_data[["date", "location_key", "cumulative_persons_vaccinated"]]
cleaned_vaccinations_data = cleaned_vaccinations_data.rename(columns={"location_key": "location"})


cleaned_vaccinations_data

               date location  cumulative_persons_vaccinated
0        2021-01-25       AD                          576.0
1        2021-02-01       AD                         1036.0
2        2021-02-10       AD                         1291.0
3        2021-02-12       AD                         1622.0
4        2021-02-19       AD                         2141.0
...             ...      ...                            ...
2545113  2022-08-21       ZW                      6400632.0
2545114  2022-08-24       ZW                      6404253.0
2545115  2022-08-25       ZW                      6407937.0
2545116  2022-08-27       ZW                      6411006.0
2545117  2022-09-08       ZW                      6416614.0

[2545118 rows x 3 columns]

In [7]:
# Filtered location to US only
us_vaccinations_data = cleaned_vaccinations_data[cleaned_vaccinations_data["location"] == "US"]

us_vaccinations_data.head()

              date location  cumulative_persons_vaccinated
916955  2020-12-13       US                        30817.0
916956  2020-12-14       US                        35355.0
916957  2020-12-15       US                        81231.0
916958  2020-12-16       US                       236049.0
916959  2020-12-17       US                       502932.0